export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const TOKEN_REQUEST_SUCCESS = 'TOKEN_REQUEST_SUCCESS';
export const TOKEN_REQUEST_ERROR = 'TOKEN_REQUEST_ERROR';
export const QUESTIONS_REQUEST = 'QUESTIONS_REQUEST';
export const QUESTIONS_REQUEST_SUCCESS = 'QUESTIONS_REQUEST_SUCCESS';
export const QUESTIONS_REQUEST_ERROR = 'QUESTIONS_REQUEST_ERROR';
// export const FIND_QUESTION = 'FIND_QUESTION';
export const LOGIN = 'LOGIN';
